repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: Sort python imports
        description: This hook sorts python file imports.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Auto-format .py files
        description: This hook auto-formats staged python files according to pep8 standard.
