# Generated by Django 4.1 on 2022-08-23 07:56

from django.db import migrations

from gamification.models import Point

points_data = [
    {"role": "Absent", "points": -1},
    {"role": "Best Speaker", "points": 3},
    {"role": "Best Table Topic", "points": 3},
    {"role": "Big Three Award(TOE,TTM,GE)", "points": 3},
    {"role": "Attended Meeting", "points": 5},
    {"role": "Vote Counter", "points": 7},
    {"role": "Timer", "points": 7},
    {"role": "Speech Evaluation", "points": 7},
    {"role": "Big Three Role", "points": 6},
    {"role": "Contest Participation", "points": 10},
    {"role": "Speech", "points": 8},
    {"role": "Contest Speech", "points": 15},
    {"role": "Contest Chair", "points": 20},
    {"role": "Best Evaluator", "points": 3},
    {"role": "Toastmaster of the evening", "points": 6},
    {"role": "Table Topic Master", "points": 6},
    {"role": "General Evaluator", "points": 6},
    {"role": "TAG role", "points": 6},
    {"role": "Table Topic Evaluator", "points": 7},
]


class Migration(migrations.Migration):
    def add_point_data(apps, schema_editor):
        """Insert initial point data"""
        points = [Point(**data) for data in points_data]
        Point.objects.bulk_create(points)

    def remove_point_data(apps, schema_editor):
        """Remove initial point data"""
        roles = [point["role"] for point in points_data]
        Point.objects.filter(role__in=roles).delete()

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_point_data, remove_point_data),
    ]
