# Generated by Django 4.1 on 2022-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_awards_calculation",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
