# Generated by Django 4.1 on 2023-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_add_voting_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="creator",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="poll",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
