# Generated by Django 4.1 on 2022-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("regular_session", "Regular Session"),
                            ("joint_session", "Joint Session"),
                            ("contest", "Contest"),
                        ],
                        max_length=64,
                    ),
                ),
                ("held_on", models.DateField()),
            ],
        ),
    ]
