# Generated by Django 4.1 on 2022-08-24 12:58

from django.db import migrations

from event.models import Role
from gamification.models import Point

point_data = [
    # Basic
    {"name": "Absent", "points": -1},
    {"name": "Attended Meeting", "points": 5},
    # Speaker
    {"name": "Prepared Speaker", "points": 8},
    {"name": "Table Topic Speaker", "points": 6},
    # TAG roles
    {"name": "Vote Counter", "points": 6},
    {"name": "Timer", "points": 6},
    {"name": "Ah Counter", "points": 6},
    {"name": "Grammarian", "points": 6},
    # Evaluator
    {"name": "Table Topic Evaluator", "points": 6},
    {"name": "Prepared Speech Evaluator", "points": 6},
    # Big 3 roles
    {"name": "Toastmaster of the Evening", "points": 7},
    {"name": "Table Topic Master", "points": 7},
    {"name": "General Evaluator", "points": 7},
    # Best
    {"name": "Best Speaker", "points": 3},
    {"name": "Best Table Topic", "points": 3},
    {"name": "Best Evaluator", "points": 3},
    {"name": "Best of Big 3", "points": 3},
    # Contest
    {"name": "Contest Speaker", "points": 16},
    {"name": "Contest Participation", "points": 10},
    {"name": "Contest Chair", "points": 20},
]


class Migration(migrations.Migration):
    def add_role_points(app, schema_editor):
        points = [
            Point(role=Role.objects.get(name=data["name"]), points=data["points"])
            for data in point_data
        ]
        Point.objects.bulk_create(points)

    def remove_role_points(app, schema_editor):
        role_names = [data["name"] for data in point_data]
        Point.objects.filter(role__name__in=role_names).delete()

    dependencies = [
        ("gamification", "0001_initial"),
        ("event", "0002_point_data"),
    ]

    operations = [
        migrations.RunPython(add_role_points, remove_role_points),
    ]
