# Generated by Django 4.1 on 2022-08-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_role_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
